export function highlight(text, wordsToHighlight) {
    if (!wordsToHighlight || wordsToHighlight.length === 0) return text;

    // Escape special characters and wrap in word boundaries (\b)
    // to avoid matching "Git" inside "Digital"
    const pattern = new RegExp(`\\b(${wordsToHighlight.join("|")})\\b`, "gi");

    return text.replace(pattern, (match) => {
        // Inline styles are best for PDF generation engines
        return `<span style="font-weight: 700; color:black; padding: 0 1px; border-radius: 2px;">${match}</span>`;
    });
}

export const keywords = {
    general: [
        "Communication",
        "Teamwork",
        "Problem-solving",
        "Adaptability",
        "Leadership",
        "Time management",
        "Critical thinking",
        "Creativity",
        "Conflict resolution",
        "Attention to detail",
        "Work ethic",
        "Collaboration",
        "Organization",
        "Decision making",
        "Emotional intelligence",
    ],
    nodejs: [
        "Node.js",
        "Nodejs",
        "Express",
        "REST",
        "API",
        "Asynchronous",
        "Event-driven",
        "npm",
        "pnpm",
        "JavaScript",
        "Server-side",
        "Microservices",
        "Socket.io",
        "Authentication",
        "Authorization",
        "Optimization",
        "Testing",
        "MongoDB",
        "PostgreSQL",
    ],
    python: [
        "Python",
        "Django",
        "Flask",
        "REST",
        "API",
        "Data analysis",
        "Machine learning",
        "Pandas",
        "NumPy",
        "SQL",
        "NoSQL",
        "Testing",
        "OOP",
        "Scripting",
        "Automation",
        "Web scraping",
        "Git",
    ],
    frontend: [
        "HTML",
        "CSS",
        "JavaScript",
        "TypeScript",
        "React",
        "Vue",
        "Angular",
        "Responsive design",
        "UI",
        "UX",
        "Redux",
        "SASS",
        "SCSS",
        "Webpack",
        "Vite",
        "Accessibility",
        "Testing",
        "Svelte",
        "SvelteKit",
    ],
    backend: [
        "Server-side",
        "REST",
        "API",
        "SQL",
        "NoSQL",
        "Authentication",
        "Authorization",
        "Microservices",
        "Caching",
        "Node.js",
        "NodeJS",
        "Python",
        "Java",
        "Optimization",
        "Security",
        "Testing",
        "Docker",
        "CI/CD",
        "AWS",
        "Azure",
        "GCP",
        "Logging",
        "Monitoring",
        "SvelteKit",
    ],
    fullstack: [
        "Full-stack",
        "Front-end",
        "Back-end",
        "REST",
        "GraphQL",
        "Database",
        "Git",
        "Responsive",
        "Authentication",
        "Authorization",
        "Testing",
        "CI/CD",
        "Cloud",
        "Microservices",
        "Problem-solving",
        "Agile",
        "Svelte",
        "SvelteKit",
    ],
};
