export const keywords = [
    "Communication",
    "Teamwork",
    "Problem-solving",
    "Adaptability",
    "Leadership",
    "Time management",
    "Critical thinking",
    "Creativity",
    "Conflict resolution",
    "Attention to detail",
    "Work ethic",
    "Collaboration",
    "Organization",
    "Decision making",
    "Emotional intelligence",
    "Node.js",
    "Nodejs",
    "Express",
    "REST",
    "API",
    "Asynchronous",
    "Event-driven",
    "npm",
    "pnpm",
    "JavaScript",
    "Server-side",
    "Microservices",
    "Socket.io",
    "Authentication",
    "Authorization",
    "Optimization",
    "Testing",
    "MongoDB",
    "PostgreSQL",
    "Python",
    "Django",
    "Flask",
    "REST",
    "API",
    "Data analysis",
    "Machine learning",
    "Pandas",
    "NumPy",
    "SQL",
    "NoSQL",
    "Testing",
    "OOP",
    "Scripting",
    "Automation",
    "Web scraping",
    "Git",
    "HTML",
    "CSS",
    "JavaScript",
    "TypeScript",
    "React",
    "Vue",
    "Angular",
    "Responsive design",
    "UI",
    "UX",
    "Redux",
    "SASS",
    "SCSS",
    "Webpack",
    "Vite",
    "Accessibility",
    "Testing",
    "Svelte",
    "SvelteKit",
    "Server-side",
    "REST",
    "API",
    "SQL",
    "NoSQL",
    "Authentication",
    "Authorization",
    "Microservices",
    "Caching",
    "Node.js",
    "NodeJS",
    "Python",
    "Java",
    "Optimization",
    "Security",
    "Testing",
    "Docker",
    "CI/CD",
    "AWS",
    "Azure",
    "GCP",
    "Logging",
    "Monitoring",
    "SvelteKit",
    "Full-stack",
    "Front-end",
    "Back-end",
    "REST",
    "GraphQL",
    "Database",
    "Git",
    "Responsive",
    "Authentication",
    "Authorization",
    "Testing",
    "CI/CD",
    "Cloud",
    "Microservices",
    "Problem-solving",
    "Agile",
    "Svelte",
    "SvelteKit",
];

export function highlight(text) {
    let wordsToHighlight = keywords;
    if (!wordsToHighlight || wordsToHighlight.length === 0) return text;

    // Escape special characters and wrap in word boundaries (\b)
    // to avoid matching "Git" inside "Digital"
    const pattern = new RegExp(`\\b(${wordsToHighlight.join("|")})\\b`, "gi");

    return text.replace(pattern, (match) => {
        // Inline styles are best for PDF generation engines
        return `<span style="font-weight: 700; color:black; padding: 0 1px; border-radius: 2px;">${match}</span>`;
    });
}
